"""Add relationships and team_name to standings

Revision ID: ece2ff06a99b
Revises: 24ca4c0b5e6e
Create Date: 2025-11-27 14:59:32.012180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ece2ff06a99b'
down_revision: Union[str, Sequence[str], None] = '24ca4c0b5e6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standings', sa.Column('team_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('standings', 'team_name')
    # ### end Alembic commands ###
